export default function Head() {
    return (
        <>
            <title>Fanrong Creative Studio</title>
            {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
            <meta name="viewport" content="width=1920"></meta>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Explore Fanrong's Studio | Discover a world of innovative design solutions, artistic craftsmanship, and cutting-edge creativity. Our design product studio showcases a diverse range of projects that inspire and captivate. Explore our portfolio today." />
            <meta name="keywords" content="design, product, studio, portfolio, creativity, innovation" />
            <meta name="author" content="Fanrong Studio" />

            <meta property="og:title" content="Fanrong Studio - Home" />
            <meta property="og:description" content="Explore Fanrong's Studio | Discover a world of innovative design solutions, artistic craftsmanship, and cutting-edge creativity. Our design product studio showcases a diverse range of projects that inspire and captivate. Explore our portfolio today." />
            <meta property="og:image" content="https://www.yourwebsite.com/images/your-image.jpg" />
            <meta property="og:url" content="https://www.yourwebsite.com" />

            <meta name="twitter:card" content="summary_large_image" />
            <meta name="twitter:site" content="@yourtwitterhandle" />
        </>
    )
}